version: "1"
services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports: 
      - 5432:5432
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ammar@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: pass123
    ports:
      -  82:80 
    